name: Codecov workflow
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [16,  17, 18, 19]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install
      - run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
